//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int reservation_id { get; set; }
        public System.DateTime date { get; set; }
        public int time_slot_id { get; set; }
        public int table_id { get; set; }
        public int user_id { get; set; }
    
        public virtual table table { get; set; }
        public virtual time_slots time_slots { get; set; }
        public virtual user user { get; set; }
    }
}
